[package]
name = "fastcosine"
version = "0.1.0"
authors = ["Luiz Berti <luizberti@users.noreply.github.com>"]

[dependencies]
rayon = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
float-ord = "*"
chrono = "*"
clap = "*"